//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.12 at 08:40:23 PM CDT 
//


package edu.umsl.cs.group4.services.rotation.beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.umsl.cs.group4.services.rotation.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.umsl.cs.group4.services.rotation.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Rotations.RotationYear.Course.RotationTerm }
     * 
     */
    public Rotations.RotationYear.Course.RotationTerm createRotationsRotationYearCourseRotationTerm() {
        return new Rotations.RotationYear.Course.RotationTerm();
    }

    /**
     * Create an instance of {@link Rotations.RotationYear }
     * 
     */
    public Rotations.RotationYear createRotationsRotationYear() {
        return new Rotations.RotationYear();
    }

    /**
     * Create an instance of {@link Rotations }
     * 
     */
    public Rotations createRotations() {
        return new Rotations();
    }

    /**
     * Create an instance of {@link Rotations.RotationYear.Course }
     * 
     */
    public Rotations.RotationYear.Course createRotationsRotationYearCourse() {
        return new Rotations.RotationYear.Course();
    }

}
