//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.12 at 08:40:23 PM CDT 
//


package edu.umsl.cs.group4.services.rotation.beans;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rotation_year" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="course" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="course_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="course_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="rotation_term" maxOccurs="2" minOccurs="2">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="term" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="time_code">
 *                                         &lt;simpleType>
 *                                           &lt;list itemType="{http://www.w3.org/2001/XMLSchema}string" />
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rotationYear"
})
@XmlRootElement(name = "Rotations")
public class Rotations {

    @XmlElement(name = "rotation_year", required = true)
    protected List<Rotations.RotationYear> rotationYear;

    /**
     * Gets the value of the rotationYear property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rotationYear property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRotationYear().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Rotations.RotationYear }
     * 
     * 
     */
    public List<Rotations.RotationYear> getRotationYear() {
        if (rotationYear == null) {
            rotationYear = new ArrayList<Rotations.RotationYear>();
        }
        return this.rotationYear;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="course" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="course_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="course_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="rotation_term" maxOccurs="2" minOccurs="2">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="term" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="time_code">
     *                               &lt;simpleType>
     *                                 &lt;list itemType="{http://www.w3.org/2001/XMLSchema}string" />
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "year",
        "course"
    })
    public static class RotationYear {

        @XmlElement(required = true)
        protected BigInteger year;
        @XmlElement(required = true)
        protected List<Rotations.RotationYear.Course> course;

        /**
         * Gets the value of the year property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getYear() {
            return year;
        }

        /**
         * Sets the value of the year property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setYear(BigInteger value) {
            this.year = value;
        }

        /**
         * Gets the value of the course property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the course property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCourse().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Rotations.RotationYear.Course }
         * 
         * 
         */
        public List<Rotations.RotationYear.Course> getCourse() {
            if (course == null) {
                course = new ArrayList<Rotations.RotationYear.Course>();
            }
            return this.course;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="course_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="course_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="rotation_term" maxOccurs="2" minOccurs="2">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="term" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="time_code">
         *                     &lt;simpleType>
         *                       &lt;list itemType="{http://www.w3.org/2001/XMLSchema}string" />
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "subject",
            "courseNumber",
            "courseName",
            "rotationTerm"
        })
        public static class Course {

            @XmlElement(required = true)
            protected String subject;
            @XmlElement(name = "course_number", required = true)
            protected String courseNumber;
            @XmlElement(name = "course_name", required = true)
            protected String courseName;
            @XmlElement(name = "rotation_term", required = true)
            protected List<Rotations.RotationYear.Course.RotationTerm> rotationTerm;

            /**
             * Gets the value of the subject property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSubject() {
                return subject;
            }

            /**
             * Sets the value of the subject property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSubject(String value) {
                this.subject = value;
            }

            /**
             * Gets the value of the courseNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCourseNumber() {
                return courseNumber;
            }

            /**
             * Sets the value of the courseNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCourseNumber(String value) {
                this.courseNumber = value;
            }

            /**
             * Gets the value of the courseName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCourseName() {
                return courseName;
            }

            /**
             * Sets the value of the courseName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCourseName(String value) {
                this.courseName = value;
            }

            /**
             * Gets the value of the rotationTerm property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the rotationTerm property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getRotationTerm().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Rotations.RotationYear.Course.RotationTerm }
             * 
             * 
             */
            public List<Rotations.RotationYear.Course.RotationTerm> getRotationTerm() {
                if (rotationTerm == null) {
                    rotationTerm = new ArrayList<Rotations.RotationYear.Course.RotationTerm>();
                }
                return this.rotationTerm;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="term" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="time_code">
             *           &lt;simpleType>
             *             &lt;list itemType="{http://www.w3.org/2001/XMLSchema}string" />
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "term",
                "timeCode"
            })
            public static class RotationTerm {

                @XmlElement(required = true)
                protected String term;
                @XmlList
                @XmlElement(name = "time_code", required = true, nillable = true)
                protected List<String> timeCode;

                /**
                 * Gets the value of the term property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTerm() {
                    return term;
                }

                /**
                 * Sets the value of the term property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTerm(String value) {
                    this.term = value;
                }

                /**
                 * Gets the value of the timeCode property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the timeCode property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getTimeCode().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getTimeCode() {
                    if (timeCode == null) {
                        timeCode = new ArrayList<String>();
                    }
                    return this.timeCode;
                }

            }

        }

    }

}
