//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.27 at 10:03:03 PM CST 
//


package edu.umsl.cs.group4.services.descriptions.beans;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="course" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="course_number" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="course_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="credit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="course_description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="can_select_multiple" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="prerequisite" minOccurs="0" form="qualified">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="or_choice" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="and_required" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;simpleType>
 *                                           &lt;list itemType="{http://www.w3.org/2001/XMLSchema}string" />
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="additional_preq" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "course"
})
@XmlRootElement(name = "descriptions")
public class Descriptions {

    @XmlElement(required = true)
    protected List<Descriptions.Course> course;

    /**
     * Gets the value of the course property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the course property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCourse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Descriptions.Course }
     * 
     * 
     */
    public List<Descriptions.Course> getCourse() {
        if (course == null) {
            course = new ArrayList<Descriptions.Course>();
        }
        return this.course;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="course_number" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="course_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="credit" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="course_description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="can_select_multiple" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="prerequisite" minOccurs="0" form="qualified">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="or_choice" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="and_required" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;list itemType="{http://www.w3.org/2001/XMLSchema}string" />
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="additional_preq" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "subject",
        "courseNumber",
        "courseName",
        "credit",
        "courseDescription",
        "canSelectMultiple",
        "prerequisite"
    })
    public static class Course {

		@XmlElement(required = true)
        protected String subject;
        @XmlElement(name = "course_number", required = true)
        protected Integer courseNumber;
        @XmlElement(name = "course_name", required = true)
        protected String courseName;
        @XmlElement(required = true)
        protected String credit;
        @XmlElement(name = "course_description", required = true)
        protected String courseDescription;
        @XmlElement(name = "can_select_multiple")
        protected Boolean canSelectMultiple;
        protected Descriptions.Course.Prerequisite prerequisite;

        /**
         * Gets the value of the subject property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubject() {
            return subject;
        }

        /**
         * Sets the value of the subject property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubject(String value) {
            this.subject = value;
        }

        /**
         * Gets the value of the courseNumber property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public Integer getCourseNumber() {
            return courseNumber;
        }

        /**
         * Sets the value of the courseNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCourseNumber(Integer value) {
            this.courseNumber = value;
        }

        /**
         * Gets the value of the courseName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCourseName() {
            return courseName;
        }

        /**
         * Sets the value of the courseName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCourseName(String value) {
            this.courseName = value;
        }

        /**
         * Gets the value of the credit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCredit() {
            return credit;
        }

        /**
         * Sets the value of the credit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCredit(String value) {
            this.credit = value;
        }

        /**
         * Gets the value of the courseDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCourseDescription() {
            return courseDescription;
        }

        /**
         * Sets the value of the courseDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCourseDescription(String value) {
            this.courseDescription = value;
        }

        /**
         * Gets the value of the canSelectMultiple property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isCanSelectMultiple() {
            return canSelectMultiple;
        }

        /**
         * Sets the value of the canSelectMultiple property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setCanSelectMultiple(Boolean value) {
            this.canSelectMultiple = value;
        }

        /**
         * Gets the value of the prerequisite property.
         * 
         * @return
         *     possible object is
         *     {@link Descriptions.Course.Prerequisite }
         *     
         */
        public Descriptions.Course.Prerequisite getPrerequisite() {
            return prerequisite;
        }

        /**
         * Sets the value of the prerequisite property.
         * 
         * @param value
         *     allowed object is
         *     {@link Descriptions.Course.Prerequisite }
         *     
         */
        public void setPrerequisite(Descriptions.Course.Prerequisite value) {
            this.prerequisite = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="or_choice" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="and_required" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;list itemType="{http://www.w3.org/2001/XMLSchema}string" />
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="additional_preq" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "orChoice",
            "additionalPreq"
        })
        public static class Prerequisite {

            @XmlElement(name = "or_choice")
            protected Descriptions.Course.Prerequisite.OrChoice orChoice;
            @XmlElement(name = "additional_preq")
            protected String additionalPreq;

            /**
             * Gets the value of the orChoice property.
             * 
             * @return
             *     possible object is
             *     {@link Descriptions.Course.Prerequisite.OrChoice }
             *     
             */
            public Descriptions.Course.Prerequisite.OrChoice getOrChoice() {
                return orChoice;
            }

            /**
             * Sets the value of the orChoice property.
             * 
             * @param value
             *     allowed object is
             *     {@link Descriptions.Course.Prerequisite.OrChoice }
             *     
             */
            public void setOrChoice(Descriptions.Course.Prerequisite.OrChoice value) {
                this.orChoice = value;
            }

            /**
             * Gets the value of the additionalPreq property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAdditionalPreq() {
                return additionalPreq;
            }

            /**
             * Sets the value of the additionalPreq property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAdditionalPreq(String value) {
                this.additionalPreq = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="and_required" maxOccurs="unbounded" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;list itemType="{http://www.w3.org/2001/XMLSchema}string" />
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "andRequired"
            })
            public static class OrChoice {

                @XmlElementRef(name = "and_required", type = JAXBElement.class, required = false)
                protected List<JAXBElement<List<String>>> andRequired;

                /**
                 * Gets the value of the andRequired property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the andRequired property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getAndRequired().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}
                 * 
                 * 
                 */
                public List<JAXBElement<List<String>>> getAndRequired() {
                    if (andRequired == null) {
                        andRequired = new ArrayList<JAXBElement<List<String>>>();
                    }
                    return this.andRequired;
                }

            }

        }

    }

}
