//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.12 at 09:01:18 PM CDT 
//


package edu.umsl.cs.group4.services.schedule.beans;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.umsl.cs.group4.services.schedule.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ScheduleScheduledCourseTerm_QNAME = new QName("", "term");
    private final static QName _ScheduleScheduledCourseSession_QNAME = new QName("", "session");
    private final static QName _ScheduleScheduledCourseYear_QNAME = new QName("", "year");
    private final static QName _ScheduleScheduledCourseSessionCourseEndDate_QNAME = new QName("", "end_date");
    private final static QName _ScheduleScheduledCourseSessionCourseInstructionMode_QNAME = new QName("", "instruction_mode");
    private final static QName _ScheduleScheduledCourseSessionCourseUncommon_QNAME = new QName("", "uncommon");
    private final static QName _ScheduleScheduledCourseSessionCourseCourseNumber_QNAME = new QName("", "course_number");
    private final static QName _ScheduleScheduledCourseSessionCourseSubject_QNAME = new QName("", "subject");
    private final static QName _ScheduleScheduledCourseSessionCourseCatalogNumber_QNAME = new QName("", "catalog_number");
    private final static QName _ScheduleScheduledCourseSessionCourseCourseName_QNAME = new QName("", "course_name");
    private final static QName _ScheduleScheduledCourseSessionCourseClassSection_QNAME = new QName("", "class_section");
    private final static QName _ScheduleScheduledCourseSessionCourseStartDate_QNAME = new QName("", "start_date");
    private final static QName _ScheduleScheduledCourseSessionCourseUncommonUncommonRecordCurrentEnrollment_QNAME = new QName("", "current_enrollment");
    private final static QName _ScheduleScheduledCourseSessionCourseUncommonUncommonRecordInstructor_QNAME = new QName("", "instructor");
    private final static QName _ScheduleScheduledCourseSessionCourseUncommonUncommonRecordEndTime_QNAME = new QName("", "end_time");
    private final static QName _ScheduleScheduledCourseSessionCourseUncommonUncommonRecordDayCode_QNAME = new QName("", "day_code");
    private final static QName _ScheduleScheduledCourseSessionCourseUncommonUncommonRecordCapacity_QNAME = new QName("", "capacity");
    private final static QName _ScheduleScheduledCourseSessionCourseUncommonUncommonRecordStartTime_QNAME = new QName("", "start_time");
    private final static QName _ScheduleScheduledCourseSessionCourseUncommonUncommonRecordRoom_QNAME = new QName("", "room");
    private final static QName _ScheduleScheduledCourseSessionCourseUncommonUncommonRecord_QNAME = new QName("", "uncommon_record");
    private final static QName _ScheduleScheduledCourse_QNAME = new QName("", "scheduled_course");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.umsl.cs.group4.services.schedule.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Schedule.ScheduledCourse.Session }
     * 
     */
    public Schedule.ScheduledCourse.Session createScheduleScheduledCourseSession() {
        return new Schedule.ScheduledCourse.Session();
    }

    /**
     * Create an instance of {@link Schedule.ScheduledCourse }
     * 
     */
    public Schedule.ScheduledCourse createScheduleScheduledCourse() {
        return new Schedule.ScheduledCourse();
    }

    /**
     * Create an instance of {@link Schedule.ScheduledCourse.Session.Course }
     * 
     */
    public Schedule.ScheduledCourse.Session.Course createScheduleScheduledCourseSessionCourse() {
        return new Schedule.ScheduledCourse.Session.Course();
    }

    /**
     * Create an instance of {@link Schedule.ScheduledCourse.Session.Course.Uncommon.UncommonRecord }
     * 
     */
    public Schedule.ScheduledCourse.Session.Course.Uncommon.UncommonRecord createScheduleScheduledCourseSessionCourseUncommonUncommonRecord() {
        return new Schedule.ScheduledCourse.Session.Course.Uncommon.UncommonRecord();
    }

    /**
     * Create an instance of {@link Schedule.ScheduledCourse.Session.Course.Uncommon }
     * 
     */
    public Schedule.ScheduledCourse.Session.Course.Uncommon createScheduleScheduledCourseSessionCourseUncommon() {
        return new Schedule.ScheduledCourse.Session.Course.Uncommon();
    }

    /**
     * Create an instance of {@link Schedule }
     * 
     */
    public Schedule createSchedule() {
        return new Schedule();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "term", scope = Schedule.ScheduledCourse.class)
    public JAXBElement<String> createScheduleScheduledCourseTerm(String value) {
        return new JAXBElement<String>(_ScheduleScheduledCourseTerm_QNAME, String.class, Schedule.ScheduledCourse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Schedule.ScheduledCourse.Session }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "session", scope = Schedule.ScheduledCourse.class)
    public JAXBElement<Schedule.ScheduledCourse.Session> createScheduleScheduledCourseSession(Schedule.ScheduledCourse.Session value) {
        return new JAXBElement<Schedule.ScheduledCourse.Session>(_ScheduleScheduledCourseSession_QNAME, Schedule.ScheduledCourse.Session.class, Schedule.ScheduledCourse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "year", scope = Schedule.ScheduledCourse.class)
    public JAXBElement<Integer> createScheduleScheduledCourseYear(Integer value) {
        return new JAXBElement<Integer>(_ScheduleScheduledCourseYear_QNAME, Integer.class, Schedule.ScheduledCourse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "end_date", scope = Schedule.ScheduledCourse.Session.Course.class)
    public JAXBElement<String> createScheduleScheduledCourseSessionCourseEndDate(String value) {
        return new JAXBElement<String>(_ScheduleScheduledCourseSessionCourseEndDate_QNAME, String.class, Schedule.ScheduledCourse.Session.Course.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "instruction_mode", scope = Schedule.ScheduledCourse.Session.Course.class)
    public JAXBElement<String> createScheduleScheduledCourseSessionCourseInstructionMode(String value) {
        return new JAXBElement<String>(_ScheduleScheduledCourseSessionCourseInstructionMode_QNAME, String.class, Schedule.ScheduledCourse.Session.Course.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Schedule.ScheduledCourse.Session.Course.Uncommon }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "uncommon", scope = Schedule.ScheduledCourse.Session.Course.class)
    public JAXBElement<Schedule.ScheduledCourse.Session.Course.Uncommon> createScheduleScheduledCourseSessionCourseUncommon(Schedule.ScheduledCourse.Session.Course.Uncommon value) {
        return new JAXBElement<Schedule.ScheduledCourse.Session.Course.Uncommon>(_ScheduleScheduledCourseSessionCourseUncommon_QNAME, Schedule.ScheduledCourse.Session.Course.Uncommon.class, Schedule.ScheduledCourse.Session.Course.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "course_number", scope = Schedule.ScheduledCourse.Session.Course.class)
    public JAXBElement<Integer> createScheduleScheduledCourseSessionCourseCourseNumber(Integer value) {
        return new JAXBElement<Integer>(_ScheduleScheduledCourseSessionCourseCourseNumber_QNAME, Integer.class, Schedule.ScheduledCourse.Session.Course.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "subject", scope = Schedule.ScheduledCourse.Session.Course.class)
    public JAXBElement<String> createScheduleScheduledCourseSessionCourseSubject(String value) {
        return new JAXBElement<String>(_ScheduleScheduledCourseSessionCourseSubject_QNAME, String.class, Schedule.ScheduledCourse.Session.Course.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "catalog_number", scope = Schedule.ScheduledCourse.Session.Course.class)
    public JAXBElement<Integer> createScheduleScheduledCourseSessionCourseCatalogNumber(Integer value) {
        return new JAXBElement<Integer>(_ScheduleScheduledCourseSessionCourseCatalogNumber_QNAME, Integer.class, Schedule.ScheduledCourse.Session.Course.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "course_name", scope = Schedule.ScheduledCourse.Session.Course.class)
    public JAXBElement<String> createScheduleScheduledCourseSessionCourseCourseName(String value) {
        return new JAXBElement<String>(_ScheduleScheduledCourseSessionCourseCourseName_QNAME, String.class, Schedule.ScheduledCourse.Session.Course.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "class_section", scope = Schedule.ScheduledCourse.Session.Course.class)
    public JAXBElement<String> createScheduleScheduledCourseSessionCourseClassSection(String value) {
        return new JAXBElement<String>(_ScheduleScheduledCourseSessionCourseClassSection_QNAME, String.class, Schedule.ScheduledCourse.Session.Course.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "start_date", scope = Schedule.ScheduledCourse.Session.Course.class)
    public JAXBElement<String> createScheduleScheduledCourseSessionCourseStartDate(String value) {
        return new JAXBElement<String>(_ScheduleScheduledCourseSessionCourseStartDate_QNAME, String.class, Schedule.ScheduledCourse.Session.Course.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "current_enrollment", scope = Schedule.ScheduledCourse.Session.Course.Uncommon.UncommonRecord.class)
    public JAXBElement<Integer> createScheduleScheduledCourseSessionCourseUncommonUncommonRecordCurrentEnrollment(Integer value) {
        return new JAXBElement<Integer>(_ScheduleScheduledCourseSessionCourseUncommonUncommonRecordCurrentEnrollment_QNAME, Integer.class, Schedule.ScheduledCourse.Session.Course.Uncommon.UncommonRecord.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "instructor", scope = Schedule.ScheduledCourse.Session.Course.Uncommon.UncommonRecord.class)
    public JAXBElement<String> createScheduleScheduledCourseSessionCourseUncommonUncommonRecordInstructor(String value) {
        return new JAXBElement<String>(_ScheduleScheduledCourseSessionCourseUncommonUncommonRecordInstructor_QNAME, String.class, Schedule.ScheduledCourse.Session.Course.Uncommon.UncommonRecord.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "end_time", scope = Schedule.ScheduledCourse.Session.Course.Uncommon.UncommonRecord.class)
    public JAXBElement<String> createScheduleScheduledCourseSessionCourseUncommonUncommonRecordEndTime(String value) {
        return new JAXBElement<String>(_ScheduleScheduledCourseSessionCourseUncommonUncommonRecordEndTime_QNAME, String.class, Schedule.ScheduledCourse.Session.Course.Uncommon.UncommonRecord.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "day_code", scope = Schedule.ScheduledCourse.Session.Course.Uncommon.UncommonRecord.class)
    public JAXBElement<String> createScheduleScheduledCourseSessionCourseUncommonUncommonRecordDayCode(String value) {
        return new JAXBElement<String>(_ScheduleScheduledCourseSessionCourseUncommonUncommonRecordDayCode_QNAME, String.class, Schedule.ScheduledCourse.Session.Course.Uncommon.UncommonRecord.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "capacity", scope = Schedule.ScheduledCourse.Session.Course.Uncommon.UncommonRecord.class)
    public JAXBElement<Integer> createScheduleScheduledCourseSessionCourseUncommonUncommonRecordCapacity(Integer value) {
        return new JAXBElement<Integer>(_ScheduleScheduledCourseSessionCourseUncommonUncommonRecordCapacity_QNAME, Integer.class, Schedule.ScheduledCourse.Session.Course.Uncommon.UncommonRecord.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "start_time", scope = Schedule.ScheduledCourse.Session.Course.Uncommon.UncommonRecord.class)
    public JAXBElement<String> createScheduleScheduledCourseSessionCourseUncommonUncommonRecordStartTime(String value) {
        return new JAXBElement<String>(_ScheduleScheduledCourseSessionCourseUncommonUncommonRecordStartTime_QNAME, String.class, Schedule.ScheduledCourse.Session.Course.Uncommon.UncommonRecord.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "room", scope = Schedule.ScheduledCourse.Session.Course.Uncommon.UncommonRecord.class)
    public JAXBElement<String> createScheduleScheduledCourseSessionCourseUncommonUncommonRecordRoom(String value) {
        return new JAXBElement<String>(_ScheduleScheduledCourseSessionCourseUncommonUncommonRecordRoom_QNAME, String.class, Schedule.ScheduledCourse.Session.Course.Uncommon.UncommonRecord.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Schedule.ScheduledCourse.Session.Course.Uncommon.UncommonRecord }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "uncommon_record", scope = Schedule.ScheduledCourse.Session.Course.Uncommon.class)
    public JAXBElement<Schedule.ScheduledCourse.Session.Course.Uncommon.UncommonRecord> createScheduleScheduledCourseSessionCourseUncommonUncommonRecord(Schedule.ScheduledCourse.Session.Course.Uncommon.UncommonRecord value) {
        return new JAXBElement<Schedule.ScheduledCourse.Session.Course.Uncommon.UncommonRecord>(_ScheduleScheduledCourseSessionCourseUncommonUncommonRecord_QNAME, Schedule.ScheduledCourse.Session.Course.Uncommon.UncommonRecord.class, Schedule.ScheduledCourse.Session.Course.Uncommon.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Schedule.ScheduledCourse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "scheduled_course", scope = Schedule.class)
    public JAXBElement<Schedule.ScheduledCourse> createScheduleScheduledCourse(Schedule.ScheduledCourse value) {
        return new JAXBElement<Schedule.ScheduledCourse>(_ScheduleScheduledCourse_QNAME, Schedule.ScheduledCourse.class, Schedule.class, value);
    }

}
