//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.12 at 09:01:18 PM CDT 
//


package edu.umsl.cs.group4.services.schedule.beans;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="scheduled_course" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="term" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="session" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="session_name" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                             &lt;element name="course" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="course_number" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="course_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="catalog_number" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="class_section" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="start_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="end_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="instruction_mode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="uncommon">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="uncommon_record" maxOccurs="unbounded" form="unqualified">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="start_time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="end_time" type="{http://www.w3.org/2001/XMLSchema}string" form="qualified"/>
 *                                                           &lt;element name="instructor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="room" type="{http://www.w3.org/2001/XMLSchema}string" form="qualified"/>
 *                                                           &lt;element name="day_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="capacity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                           &lt;element name="current_enrollment" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "schedule")
public class Schedule {

    @XmlElementRef(name = "scheduled_course", type = JAXBElement.class)
    @XmlMixed
    protected List<Serializable> content;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * {@link JAXBElement }{@code <}{@link Schedule.ScheduledCourse }{@code >}
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="term" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="session" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="session_name" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                   &lt;element name="course" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="course_number" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="course_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="catalog_number" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="class_section" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="start_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="end_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="instruction_mode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="uncommon">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="uncommon_record" maxOccurs="unbounded" form="unqualified">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="start_time" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="end_time" type="{http://www.w3.org/2001/XMLSchema}string" form="qualified"/>
     *                                                 &lt;element name="instructor" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="room" type="{http://www.w3.org/2001/XMLSchema}string" form="qualified"/>
     *                                                 &lt;element name="day_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="capacity" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                                 &lt;element name="current_enrollment" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class ScheduledCourse {

        @XmlElementRefs({
            @XmlElementRef(name = "term", type = JAXBElement.class),
            @XmlElementRef(name = "year", type = JAXBElement.class),
            @XmlElementRef(name = "session", type = JAXBElement.class)
        })
        @XmlMixed
        protected List<Serializable> content;

        /**
         * Gets the value of the content property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link Integer }{@code >}
         * {@link String }
         * {@link JAXBElement }{@code <}{@link Schedule.ScheduledCourse.Session }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * 
         * 
         */
        public List<Serializable> getContent() {
            if (content == null) {
                content = new ArrayList<Serializable>();
            }
            return this.content;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="session_name" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *         &lt;element name="course" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="course_number" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="course_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="catalog_number" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="class_section" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="start_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="end_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="instruction_mode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="uncommon">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="uncommon_record" maxOccurs="unbounded" form="unqualified">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="start_time" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="end_time" type="{http://www.w3.org/2001/XMLSchema}string" form="qualified"/>
         *                                       &lt;element name="instructor" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="room" type="{http://www.w3.org/2001/XMLSchema}string" form="qualified"/>
         *                                       &lt;element name="day_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="capacity" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                                       &lt;element name="current_enrollment" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "sessionName",
            "course"
        })
        public static class Session {

            @XmlElement(name = "session_name", required = true)
            protected Object sessionName;
            @XmlElement(required = true)
            protected List<Schedule.ScheduledCourse.Session.Course> course;

            /**
             * Gets the value of the sessionName property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getSessionName() {
                return sessionName;
            }

            /**
             * Sets the value of the sessionName property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setSessionName(Object value) {
                this.sessionName = value;
            }

            /**
             * Gets the value of the course property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the course property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCourse().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Schedule.ScheduledCourse.Session.Course }
             * 
             * 
             */
            public List<Schedule.ScheduledCourse.Session.Course> getCourse() {
                if (course == null) {
                    course = new ArrayList<Schedule.ScheduledCourse.Session.Course>();
                }
                return this.course;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="course_number" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="course_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="catalog_number" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="class_section" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="start_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="end_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="instruction_mode" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="uncommon">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="uncommon_record" maxOccurs="unbounded" form="unqualified">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="start_time" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="end_time" type="{http://www.w3.org/2001/XMLSchema}string" form="qualified"/>
             *                             &lt;element name="instructor" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="room" type="{http://www.w3.org/2001/XMLSchema}string" form="qualified"/>
             *                             &lt;element name="day_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="capacity" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                             &lt;element name="current_enrollment" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "content"
            })
            public static class Course {

                @XmlElementRefs({
                    @XmlElementRef(name = "subject", type = JAXBElement.class),
                    @XmlElementRef(name = "course_number", type = JAXBElement.class),
                    @XmlElementRef(name = "start_date", type = JAXBElement.class),
                    @XmlElementRef(name = "catalog_number", type = JAXBElement.class),
                    @XmlElementRef(name = "course_name", type = JAXBElement.class),
                    @XmlElementRef(name = "uncommon", type = JAXBElement.class),
                    @XmlElementRef(name = "class_section", type = JAXBElement.class),
                    @XmlElementRef(name = "instruction_mode", type = JAXBElement.class),
                    @XmlElementRef(name = "end_date", type = JAXBElement.class)
                })
                @XmlMixed
                protected List<Serializable> content;

                /**
                 * Gets the value of the content property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the content property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getContent().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link JAXBElement }{@code <}{@link Integer }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link Integer }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link Schedule.ScheduledCourse.Session.Course.Uncommon }{@code >}
                 * {@link String }
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * 
                 * 
                 */
                public List<Serializable> getContent() {
                    if (content == null) {
                        content = new ArrayList<Serializable>();
                    }
                    return this.content;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="uncommon_record" maxOccurs="unbounded" form="unqualified">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="start_time" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="end_time" type="{http://www.w3.org/2001/XMLSchema}string" form="qualified"/>
                 *                   &lt;element name="instructor" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="room" type="{http://www.w3.org/2001/XMLSchema}string" form="qualified"/>
                 *                   &lt;element name="day_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="capacity" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *                   &lt;element name="current_enrollment" type="{http://www.w3.org/2001/XMLSchema}int"/>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "content"
                })
                public static class Uncommon {

                    @XmlElementRef(name = "uncommon_record", type = JAXBElement.class)
                    @XmlMixed
                    protected List<Serializable> content;

                    /**
                     * Gets the value of the content property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the content property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getContent().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link String }
                     * {@link JAXBElement }{@code <}{@link Schedule.ScheduledCourse.Session.Course.Uncommon.UncommonRecord }{@code >}
                     * 
                     * 
                     */
                    public List<Serializable> getContent() {
                        if (content == null) {
                            content = new ArrayList<Serializable>();
                        }
                        return this.content;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="start_time" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="end_time" type="{http://www.w3.org/2001/XMLSchema}string" form="qualified"/>
                     *         &lt;element name="instructor" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="room" type="{http://www.w3.org/2001/XMLSchema}string" form="qualified"/>
                     *         &lt;element name="day_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="capacity" type="{http://www.w3.org/2001/XMLSchema}int"/>
                     *         &lt;element name="current_enrollment" type="{http://www.w3.org/2001/XMLSchema}int"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "content"
                    })
                    public static class UncommonRecord {

                        @XmlElementRefs({
                            @XmlElementRef(name = "capacity", type = JAXBElement.class),
                            @XmlElementRef(name = "room", type = JAXBElement.class),
                            @XmlElementRef(name = "day_code", type = JAXBElement.class),
                            @XmlElementRef(name = "start_time", type = JAXBElement.class),
                            @XmlElementRef(name = "instructor", type = JAXBElement.class),
                            @XmlElementRef(name = "end_time", type = JAXBElement.class),
                            @XmlElementRef(name = "current_enrollment", type = JAXBElement.class)
                        })
                        @XmlMixed
                        protected List<Serializable> content;

                        /**
                         * Gets the value of the content property.
                         * 
                         * <p>
                         * This accessor method returns a reference to the live list,
                         * not a snapshot. Therefore any modification you make to the
                         * returned list will be present inside the JAXB object.
                         * This is why there is not a <CODE>set</CODE> method for the content property.
                         * 
                         * <p>
                         * For example, to add a new item, do as follows:
                         * <pre>
                         *    getContent().add(newItem);
                         * </pre>
                         * 
                         * 
                         * <p>
                         * Objects of the following type(s) are allowed in the list
                         * {@link JAXBElement }{@code <}{@link String }{@code >}
                         * {@link String }
                         * {@link JAXBElement }{@code <}{@link String }{@code >}
                         * {@link JAXBElement }{@code <}{@link String }{@code >}
                         * {@link JAXBElement }{@code <}{@link String }{@code >}
                         * {@link JAXBElement }{@code <}{@link Integer }{@code >}
                         * {@link JAXBElement }{@code <}{@link Integer }{@code >}
                         * {@link JAXBElement }{@code <}{@link String }{@code >}
                         * 
                         * 
                         */
                        public List<Serializable> getContent() {
                            if (content == null) {
                                content = new ArrayList<Serializable>();
                            }
                            return this.content;
                        }

                    }

                }

            }

        }

    }

}
